#!/bin/sh
# Shows installed packages, ordered decreasingly by install size.
# Works for both Arch Linux and Debian-based distributions.
if [[ "$(lsb_release -i -s)" =~ .*[Aa]rch.* ]]; then
    LANG=C pacman -Qi | awk '/^Name/ {pkg=$3} /Size/ {print $4$5,pkg}' | sort -n
else
    dpkg-query -W --showformat='${Installed-Size} ${Package}\n' | sort -n
fi

